server {
    listen 80;
    servername ;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://aroma-backend-alb-1937240674.us-east-1.elb.amazonaws.com/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}